export const ErrorCode = {
  SKILL_NOT_FOUND: 'SKILL_NOT_FOUND',
  INVALID_SKILL: 'INVALID_SKILL',
  AGENT_NOT_DETECTED: 'AGENT_NOT_DETECTED',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  GIT_NOT_FOUND: 'GIT_NOT_FOUND',
  GIT_COMMAND_FAILED: 'GIT_COMMAND_FAILED',
  GIT_NOT_INITIALIZED: 'GIT_NOT_INITIALIZED',
  GIT_REMOTE_NOT_FOUND: 'GIT_REMOTE_NOT_FOUND',
  GIT_CONFLICT: 'GIT_CONFLICT',
  GIT_DIRTY: 'GIT_DIRTY',
  GIT_PUSH_REJECTED: 'GIT_PUSH_REJECTED',
  GIT_UNAVAILABLE: 'GIT_UNAVAILABLE',
  GITHUB_NOT_CONNECTED: 'GITHUB_NOT_CONNECTED',
  GITHUB_UNAVAILABLE: 'GITHUB_UNAVAILABLE',
  GITHUB_AUTHORIZATION_DENIED: 'GITHUB_AUTHORIZATION_DENIED',
  GITHUB_AUTHORIZATION_EXPIRED: 'GITHUB_AUTHORIZATION_EXPIRED',
  LOCKFILE_OUTDATED: 'LOCKFILE_OUTDATED',
  SECRET_FOUND: 'SECRET_FOUND',
  INTEGRITY_MISMATCH: 'INTEGRITY_MISMATCH',
  INVALID_MANIFEST: 'INVALID_MANIFEST',
  MANIFEST_NOT_FOUND: 'MANIFEST_NOT_FOUND',
  UNSUPPORTED_MANIFEST_VERSION: 'UNSUPPORTED_MANIFEST_VERSION',
  INVALID_LOCKFILE: 'INVALID_LOCKFILE',
  LOCKFILE_NOT_FOUND: 'LOCKFILE_NOT_FOUND',
  UNSUPPORTED_LOCKFILE_VERSION: 'UNSUPPORTED_LOCKFILE_VERSION',
  UNSAFE_PATH: 'UNSAFE_PATH',
  UNSAFE_SYMLINK: 'UNSAFE_SYMLINK',
  INVALID_CONFIG: 'INVALID_CONFIG',
  INVALID_LINK_STATE: 'INVALID_LINK_STATE',
  IMPORT_CONFLICT: 'IMPORT_CONFLICT',
  SKILL_MISSING: 'SKILL_MISSING',
  SKILL_BROKEN: 'SKILL_BROKEN',
  RUNTIME_SKILL_NOT_FOUND: 'RUNTIME_SKILL_NOT_FOUND',
  AGENT_LINK_CONFLICT: 'AGENT_LINK_CONFLICT',
  REGISTRY_NOT_FOUND: 'REGISTRY_NOT_FOUND',
  REGISTRY_UNAVAILABLE: 'REGISTRY_UNAVAILABLE',
  REGISTRY_SEARCH_FAILED: 'REGISTRY_SEARCH_FAILED',
  REGISTRY_DOWNLOAD_FAILED: 'REGISTRY_DOWNLOAD_FAILED',
  SOURCE_UNSUPPORTED: 'SOURCE_UNSUPPORTED',
  SOURCE_INVALID: 'SOURCE_INVALID',
  CACHE_MISS: 'CACHE_MISS',
  CACHE_INVALID: 'CACHE_INVALID',
  INSTALL_SOURCE_UNRESOLVED: 'INSTALL_SOURCE_UNRESOLVED',
  INSTALL_DOWNLOAD_FAILED: 'INSTALL_DOWNLOAD_FAILED',
  INSTALL_INVALID_PATH: 'INSTALL_INVALID_PATH',
  INSTALL_INVALID_STRUCTURE: 'INSTALL_INVALID_STRUCTURE',
  INSTALL_SECURITY_BLOCKED: 'INSTALL_SECURITY_BLOCKED',
  INSTALL_MATERIALIZE_FAILED: 'INSTALL_MATERIALIZE_FAILED',
  INSTALL_CONFLICT: 'INSTALL_CONFLICT',
  INSTALL_AGENT_LINK_FAILED: 'INSTALL_AGENT_LINK_FAILED',
  INSTALL_ROLLBACK_FAILED: 'INSTALL_ROLLBACK_FAILED',
  // Skill Lifecycle transactions (V0.4 M17 Fork / M18 Vendor)
  LIFECYCLE_ILLEGAL_TRANSITION: 'LIFECYCLE_ILLEGAL_TRANSITION',
  LIFECYCLE_MANAGED_MODIFIED: 'LIFECYCLE_MANAGED_MODIFIED',
  LIFECYCLE_COPY_FAILED: 'LIFECYCLE_COPY_FAILED',
  LIFECYCLE_BASE_SNAPSHOT_FAILED: 'LIFECYCLE_BASE_SNAPSHOT_FAILED',
  LIFECYCLE_ROLLBACK_FAILED: 'LIFECYCLE_ROLLBACK_FAILED',
  FORK_TARGET_EXISTS: 'FORK_TARGET_EXISTS',
  FORK_FAILED: 'FORK_FAILED',
  VENDOR_TARGET_EXISTS: 'VENDOR_TARGET_EXISTS',
  VENDOR_FAILED: 'VENDOR_FAILED',
  // Diff / Merge engines (V0.4 M19 Diff / M20 Merge)
  DIFF_UPSTREAM_UNAVAILABLE: 'DIFF_UPSTREAM_UNAVAILABLE',
  DIFF_BASE_UNAVAILABLE: 'DIFF_BASE_UNAVAILABLE',
  MERGE_BINARY_CONFLICT: 'MERGE_BINARY_CONFLICT',
  MERGE_ALREADY_IN_PROGRESS: 'MERGE_ALREADY_IN_PROGRESS',
  MERGE_NOT_IN_PROGRESS: 'MERGE_NOT_IN_PROGRESS',
  MERGE_NO_BASE: 'MERGE_NO_BASE',
  MERGE_INVALID_STATE: 'MERGE_INVALID_STATE',
} as const

export type SkillboxErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

export interface SkillboxErrorOptions {
  cause?: unknown
  context?: Record<string, unknown>
  recoverable?: boolean
}

export class SkillboxError extends Error {
  readonly code: SkillboxErrorCode
  readonly context: Record<string, unknown> | undefined
  readonly recoverable: boolean

  constructor(code: SkillboxErrorCode, message: string, options: SkillboxErrorOptions = {}) {
    const { cause, context, recoverable } = options
    super(message, cause === undefined ? undefined : { cause })
    this.name = 'SkillboxError'
    this.code = code
    this.context = context
    this.recoverable = recoverable ?? false
  }
}

export function isSkillboxError(error: unknown): error is SkillboxError {
  return error instanceof SkillboxError
}
